(() => {
  'use strict';

  // Configuración local
  const CONFIG = { addressKey:'armarioCultivo.deviceAddress', nameKey:'armarioCultivo.deviceName', themeKey:'growmanager.theme', defaultAddress:'192.168.1.25', defaultName:'Armario Cultivo', pollMs:3000, timeoutMs:5000 };
  const LABELS = { none:'Sin asignar', light:'Luz', ventilation:'Ventilación', heater:'Calefacción', pump:'Bomba' };
  const MODES = { manual:'Manual', auto:'Automático' };
  const $ = id => document.getElementById(id);
  const State = { address:normalizeAddress(localStorage.getItem(CONFIG.addressKey)||CONFIG.defaultAddress), name:localStorage.getItem(CONFIG.nameKey)||CONFIG.defaultName, status:null, functions:null, config:null, hardware:null, diagnostics:null, online:null, lastSuccess:null, lostAt:null, polling:false, view:'dashboard', energyReady:false, cultivoReady:false, suspended:false, invalidEnvironmentCount:0, restarting:false, lastDhtSignature:null };
  const connectKey='growmanager.connect.enabled';
  const hardwareEnabled=localStorage.getItem(connectKey)==='true'||(localStorage.getItem(connectKey)===null&&Boolean(localStorage.getItem(CONFIG.addressKey)));
  const hardwareViews=['control','energy','automation','hardware','connection','connectAdvanced'];
  document.documentElement.dataset.connect=String(hardwareEnabled);
  function initConnect(){
    $('connectEnabled').checked=hardwareEnabled;
    $('connectEnabled').addEventListener('change',event=>{localStorage.setItem(connectKey,String(event.target.checked));location.reload()});
    const telemetry=document.querySelector('.today-device-detail');
    if(telemetry){telemetry.removeAttribute('data-dashboard-widget');telemetry.hidden=false;$('connectAdvancedContent').append(telemetry)}
  }
  let centralUserId=null,presenceTimer=null;

  // Utilidades
  function normalizeAddress(value){return String(value||'').trim().replace(/^https?:\/\//i,'').replace(/\/+$/,'')}
  function getBaseUrl(){return `http://${State.address}`}
  function escapeHtml(value){const node=document.createElement('div');node.textContent=String(value??'');return node.innerHTML}
  function params(values){const query=new URLSearchParams();Object.entries(values).forEach(([key,value])=>query.set(key,String(value)));return query.toString()}
  function formatClock(hour,minute){return Number.isInteger(hour)&&Number.isInteger(minute)?`${String(hour).padStart(2,'0')}:${String(minute).padStart(2,'0')}`:'—:—'}
  function formatUptime(value){let seconds=Number(value);if(!Number.isFinite(seconds))return'—';const days=Math.floor(seconds/86400);seconds%=86400;const hours=Math.floor(seconds/3600);const minutes=Math.floor((seconds%3600)/60);return[days&&`${days} d`,(days||hours)&&`${hours} h`,`${minutes} min`].filter(Boolean).join(' ')}
  function signalLabel(value){const r=Number(value);if(!Number.isFinite(r))return'';return r>=-55?'Excelente':r>=-67?'Buena':r>=-75?'Regular':'Débil'}
  function validEnvironmentValue(value){return value!==null&&value!==''&&Number.isFinite(Number(value))}
  function elapsed(from){if(!from)return'';const s=Math.max(0,Math.floor((Date.now()-from)/1000));if(s<60)return`${s} s`;const m=Math.floor(s/60);return m<60?`${m} min`:`${Math.floor(m/60)} h ${m%60} min`}
  const formatArs=new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0});
  function applyTheme(theme){const value=theme==='light'?'light':'dark',next=value==='light'?'oscuro':'claro',icon=value==='light'?'☾':'☀';document.documentElement.dataset.theme=value;localStorage.setItem(CONFIG.themeKey,value);document.querySelector('meta[name="theme-color"]').content=value==='light'?'#f4f6f8':'#100d18';[$('themeToggle'),$('themeToggleMobile')].forEach(button=>{button.textContent=icon;button.setAttribute('aria-label',`Activar tema ${next}`);button.title=`Activar tema ${next}`})}
  function toggleTheme(){applyTheme(document.documentElement.dataset.theme==='light'?'dark':'light')}
  function errorText(error){const code=error?.code||error?.data?.error||error?.data?.code;if(code==='function_already_assigned')return'Esta función ya está asignada a otro canal.';if(code==='relay_in_auto_mode')return'El canal está en modo automático.';if(code==='invalid_ventilation_mode')return'El modo de ventilación seleccionado no es válido.';if(code==='invalid_ventilation_config')return'Revisá el intervalo y las duraciones de ventilación.';if(error?.name==='AbortError')return'El dispositivo tardó demasiado en responder.';if(error?.status)return`El Wemos respondió con un error (HTTP ${error.status}).`;return error?.message||'No se pudo completar la operación.'}

  // API: todas las URLs parten exclusivamente de getBaseUrl().
  async function apiRequest(path,options={}){if(!hardwareEnabled)throw new Error('GrowManager Connect está desactivado.');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),CONFIG.timeoutMs);try{const response=await fetch(`${getBaseUrl()}${path}`,{method:options.method||'GET',cache:'no-store',signal:controller.signal});const text=await response.text();let data=null;if(text.trim()){try{data=JSON.parse(text)}catch{data={message:text.trim()}}}if(!response.ok||data?.error||data?.ok===false||data?.success===false){const error=new Error(data?.message||data?.error||`HTTP ${response.status}`);error.status=response.status;error.code=data?.error||data?.code||data?.message;error.data=data;throw error}return data}finally{clearTimeout(timer)}}
  function apiGet(path){return apiRequest(path)}
  function apiPost(path,values={}){const query=params(values);return apiRequest(`${path}${query?`?${query}`:''}`,{method:'POST'})}

  // Mensajes comunes
  function showMessage(id,text,type='success'){const node=$(id);node.textContent=text;node.className=`message show ${type}`}
  function clearMessage(id){const node=$(id);node.textContent='';node.className='message'}
  async function busy(button,task){const label=button.textContent;button.disabled=true;button.textContent='Guardando…';try{return await task()}finally{button.disabled=false;button.textContent=label}}

  // Estado y dashboard
  function setOnline(online){const previous=State.online;if(online){State.online=true;State.lostAt=null}else{if(State.online!==false)State.lostAt=Date.now();State.online=false}if(previous!==null&&previous!==online&&State.cultivoReady)Operations.connection(online,State.address);const text=online?'Conectado':'Desconectado';const badge=$('connectionBadge');badge.className=`status-badge ${online?'status-online':'status-offline'}`;$('connectionText').textContent=text;const mobile=$('mobileStatus');mobile.className=`mini-status ${online?'status-online':'status-offline'}`;mobile.lastElementChild.textContent=text;$('dashboardSystemsPanel')?.classList.toggle('device-offline',!online);globalThis.GrowToday?.updateDevice({online});if(!online)$('deviceSummary').textContent='Sin respuesta del Wemos. Se conservan los últimos datos conocidos.'}
  function renderOfflineTime(){if(State.online===false)$('offlineSince').textContent=`Sin conexión hace ${elapsed(State.lostAt)}`;else $('offlineSince').textContent=''}
  function dhtLogKey(){return`growmanager.dht-log.${State.address}`}
  function loadDhtLog(){try{const rows=JSON.parse(localStorage.getItem(dhtLogKey()));return Array.isArray(rows)?rows:[]}catch{return[]}}
  function recordDhtDiagnostic(dht){if(!dht)return;const signature=`${dht.state}:${dht.consecutiveFailures||0}:${dht.reinitializations||0}`;if(signature===State.lastDhtSignature)return;State.lastDhtSignature=signature;const rows=loadDhtLog();rows.push({at:Date.now(),state:dht.state,failures:Number(dht.consecutiveFailures)||0,reinitializations:Number(dht.reinitializations)||0});localStorage.setItem(dhtLogKey(),JSON.stringify(rows.slice(-16)))}
  function renderDhtDiagnostics(dht=State.diagnostics?.dht||State.status?.dht){if(!dht){$('dhtDiagnostics').innerHTML='<p class="field-help">El firmware instalado todavía no expone diagnóstico detallado del DHT.</p>';$('dhtDiagnosticLog').innerHTML='';return}const labels={ok:'Estable',intermittent:'Intermitente',offline:'Sin conexión',starting:'Iniciando'},total=Number(dht.readCount)||0,success=Number(dht.successCount)||0,rate=total?Math.round(success/total*100):0,age=Number(dht.lastSuccessAgeSeconds)||0;$('dhtDiagnostics').innerHTML=`<div><span>Estado</span><strong class="sensor-state-${escapeHtml(dht.state)}">${labels[dht.state]||escapeHtml(dht.state)}</strong></div><div><span>Lecturas correctas</span><strong>${success}/${total} · ${rate}%</strong></div><div><span>Fallos consecutivos</span><strong>${Number(dht.consecutiveFailures)||0}</strong></div><div><span>Última lectura válida</span><strong>${success?`hace ${age} s`:'Sin lectura'}</strong></div><div><span>Reinicios internos DHT</span><strong>${Number(dht.reinitializations)||0}</strong></div>`;const log=loadDhtLog().slice(-8).reverse();$('dhtDiagnosticLog').innerHTML=log.length?log.map(item=>`<p><b>${new Date(item.at).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'})}</b><span>${labels[item.state]||item.state} · ${item.failures} fallo(s)</span></p>`).join(''):'<p><span>El registro comenzará con el próximo cambio de estado.</span></p>'}
  function renderStatus(data){State.status=data;State.lastSuccess=Date.now();setOnline(data.online!==false);const temperatureValid=validEnvironmentValue(data.temperature),humidityValid=validEnvironmentValue(data.humidity),environmentValid=temperatureValid&&humidityValid&&!((Number(data.temperature)===0)&&(Number(data.humidity)===0)),dht=data.dht||{state:environmentValid?'ok':'offline',fresh:environmentValid,consecutiveFailures:environmentValid?0:3},stale=environmentValid&&dht.fresh===false,offline=dht.state==='offline'||!environmentValid;recordDhtDiagnostic(data.dht);renderDhtDiagnostics(data.dht);State.invalidEnvironmentCount=offline?State.invalidEnvironmentCount+1:0;const recovery=$('sensorRecoveryPanel');recovery.hidden=!offline&&dht.state!=='intermittent';$('sensorRecoveryTitle').textContent=offline?'Sensor ambiental sin conexión':'Lectura ambiental intermitente';$('sensorRecoveryText').textContent=offline?`El DHT acumula ${Number(dht.consecutiveFailures)||0} fallos consecutivos. Revisá el diagnóstico o reiniciá el Wemos.`:`Se conserva la última lectura válida, de hace ${Number(dht.lastSuccessAgeSeconds)||0} segundos. El firmware seguirá intentando recuperarlo.`;$('sensorRecoveryRestart').hidden=!offline;$('firmwareVersion').textContent=data.version||'—';$('temperature').textContent=environmentValid?Number(data.temperature).toFixed(1):'—';$('humidity').textContent=environmentValid?Number(data.humidity).toFixed(1):'—';document.querySelectorAll('[data-environment-metric]').forEach(card=>{card.classList.toggle('sensor-invalid',offline);card.classList.toggle('sensor-stale',stale)});$('deviceTime').textContent=formatClock(data.hour,data.minute);$('timeSync').textContent=data.timeSynced?'Sincronizada':'Sin sincronizar';$('deviceIp').textContent=data.ip||State.address;$('rssi').textContent=Number.isFinite(Number(data.rssi))?`${data.rssi} dBm`:'—';$('signalQuality').textContent=signalLabel(data.rssi);$('uptime').textContent=formatUptime(data.uptime);$('soilStatus').textContent=data.soilEnabled?(data.soil==null?'Habilitado':`${data.soil}%`):'Deshabilitado';$('lastUpdate').textContent=new Intl.DateTimeFormat('es-AR',{hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date());$('deviceSummary').textContent=offline?`${State.name} está conectado, pero el DHT no entrega datos.`:stale?`${State.name} conserva la última lectura válida mientras recupera el DHT.`:`${State.name} responde en la red local.`;globalThis.EnvironmentHistory?.track(data,data.device||State.address);GrowToday.updateDevice({online:State.online,sensorValid:!offline&&!stale,at:State.lastSuccess});renderDashboardRelays(data.relays||[]);renderOfflineTime()}
  function clock(value){const minutes=((Number(value)%1440)+1440)%1440;return`${String(Math.floor(minutes/60)).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`}
  function systemDetail(relay){const config=State.config||{};if(State.online===false)return'Último estado conocido · Wemos sin conexión';if(relay.mode==='manual')return'Control manual desde la sección Control';if(relay.function==='light'){if(config.lightTransitionActive&&config.lightTransitionUntil)return`Transición hasta ${new Date(Number(config.lightTransitionUntil)*1000).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}`;const start=Number(config.lightStartHour)*60+Number(config.lightStartMinute),end=start+Number(config.lightDurationHours||0)*60;if(Number.isFinite(start)&&Number.isFinite(end))return relay.state?`Se apaga a las ${clock(end)}`:`Se enciende a las ${clock(start)}`;return'Horario automático'}if(relay.function==='ventilation'){const mode=config.ventilationMode||'combined',interval=Number(config.ventilationIntervalMinutes);if(relay.state)return mode==='temperature'?'Emergencia por temperatura':'Ventilando ahora';if(mode==='temperature')return`Se activa al superar ${Number(config.tempMax).toLocaleString('es-AR')} °C`;if(Number.isFinite(interval)&&interval>0&&Number.isFinite(Number(State.status?.uptime))){const elapsedMinutes=Math.floor(Number(State.status.uptime)/60),remaining=interval-(elapsedMinutes%interval);return`Próximo ciclo aprox. en ${remaining} min`}return`Ciclo cada ${interval||'—'} min`}if(relay.function==='heater'){const threshold=Number(config.tempMin);return relay.state?'Elevando la temperatura':Number.isFinite(threshold)?`Se activa debajo de ${threshold.toLocaleString('es-AR')} °C`:'Regulación automática'}return'Control automático'}
  function systemCard(relay){const meta={light:['light','Luz'],ventilation:['wind','Ventilación'],heater:['heat','Calefacción']}[relay.function]||['sliders','Sistema'];return `<button class="dashboard-system" type="button" data-view="control"><span class="dashboard-system-icon">${GrowToday.icon(meta[0])}</span><span class="dashboard-system-copy"><strong>${meta[1]}</strong><em>${State.online===false?'Último estado: ':''}${relay.state?'Encendida':'Apagada'} · ${relay.mode==='auto'?'Automático':'Manual'}</em></span><span aria-hidden="true">→</span></button>`}
  function renderDashboardRelays(relays){const visible=['light','ventilation','heater'].map(name=>relays.find(relay=>relay.function===name)).filter(Boolean);$('dashboardRelays').innerHTML=visible.length?visible.map(systemCard).join(''):'<button class="dashboard-system empty" type="button" data-view="control"><span class="dashboard-system-icon">○</span><span class="dashboard-system-copy"><strong>Configurar dispositivos</strong><em>Configurá luz, ventilación o calefacción.</em></span><span class="dashboard-system-arrow">›</span></button>'}
  async function loadStatus({notify=false}={}){if(!hardwareEnabled||State.polling||State.suspended)return false;State.polling=true;try{const data=await apiGet('/api/status');if(!data||!Array.isArray(data.relays))throw new Error('La respuesta de estado no es válida.');if(State.energyReady)await Energy.trackStatus(data.relays);renderStatus(data);if(State.energyReady)await renderEnergy();if(notify)showMessage('connectionMessage',`Conexión correcta con ${data.device||State.address}.`);return true}catch(error){if(State.energyReady)Energy.markOffline();setOnline(false);renderOfflineTime();if(State.energyReady)await renderEnergy().catch(()=>{});if(notify)showMessage('connectionMessage',errorText(error),'error');return false}finally{State.polling=false}}
  const wait=milliseconds=>new Promise(resolve=>setTimeout(resolve,milliseconds));
  async function restartDevice(){if(State.restarting)return;State.restarting=true;const button=$('confirmRestartDevice');button.disabled=true;button.textContent='Reiniciando…';$('restartDeviceDialog').close();showMessage('connectionMessage','Orden enviada. Esperando que el Wemos vuelva a conectarse…','info');$('deviceSummary').textContent='Reiniciando el Wemos…';try{try{await apiPost('/api/restart')}catch(commandError){if(commandError?.status)throw commandError;console.info('El Wemos cortó la conexión para reiniciarse:',commandError?.message||commandError)}setOnline(false);await wait(4000);const deadline=Date.now()+60000;while(Date.now()<deadline){if(await loadStatus()){showMessage('connectionMessage','Wemos reiniciado y conectado correctamente.','success');State.invalidEnvironmentCount=0;$('sensorRecoveryPanel').hidden=true;return}await wait(2500)}throw new Error('El Wemos no volvió a conectarse dentro de 60 segundos. Revisá su alimentación y la red Wi-Fi.')}catch(error){showMessage('connectionMessage',errorText(error),'error');$('deviceSummary').textContent=errorText(error)}finally{State.restarting=false;button.disabled=false;button.textContent='Sí, reiniciar'}}

  // Energía estimada: configuración local + eventos IndexedDB.
  function renderEnergyConfig(){const cfg=Energy.getConfig();$('energyTariff').value=cfg.tariff;$('energyConfigFields').innerHTML=cfg.devices.map(device=>`<div class="energy-config-item" data-energy-relay="${device.relayId}"><span>RELAY ${device.relayId}</span><label>Dispositivo<input name="name${device.relayId}" value="${escapeHtml(device.name)}" maxlength="40" required></label><label>Potencia W<input name="watts${device.relayId}" value="${device.watts}" type="number" min="0" step="1" inputmode="numeric" required></label></div>`).join('')}
  async function renderEnergy(){const relays=State.status?.relays||[];const cfg=Energy.getConfig();const summary=await Energy.getSummary(relays,State.online!==false);$('dashPower').textContent=`${summary.instantW.toLocaleString('es-AR')} W`;$('dashToday').textContent=`${summary.todayKwh.toLocaleString('es-AR',{minimumFractionDigits:2,maximumFractionDigits:2})} kWh`;$('dashCost').textContent=formatArs.format(summary.todayCost);$('energyPowerW').textContent=`${summary.instantW.toLocaleString('es-AR')} W`;$('energyPowerKw').textContent=`${(summary.instantW/1000).toLocaleString('es-AR',{minimumFractionDigits:3,maximumFractionDigits:3})} kW`;$('energyToday').textContent=summary.todayKwh.toLocaleString('es-AR',{minimumFractionDigits:2,maximumFractionDigits:2});$('energyMonth').textContent=summary.monthKwh.toLocaleString('es-AR',{minimumFractionDigits:2,maximumFractionDigits:2});$('energyCostToday').textContent=formatArs.format(summary.todayCost);$('energyCostMonth').textContent=formatArs.format(summary.monthCost);const states=new Map(relays.map(r=>[Number(r.id),Boolean(r.state)]));$('energyRelays').innerHTML=cfg.devices.map(device=>{const on=State.online!==false&&states.get(device.relayId);return`<article class="energy-detail"><div><span>RELAY ${device.relayId}</span><h4>${escapeHtml(device.name)}</h4><p>Potencia nominal: ${device.watts.toLocaleString('es-AR')} W</p></div><div><span>Estado</span><strong class="${on?'on':''}">${on?'ON':'OFF'}</strong><p>${on?device.watts.toLocaleString('es-AR'):0} W actuales</p></div></article>`}).join('')}

  // Control y funciones
  async function loadFunctions(){try{const data=await apiGet('/api/functions');State.functions=data;renderControl(data.relays||State.status?.relays||[]);return data}catch(error){showMessage('controlMessage',errorText(error),'error');throw error}}
  function renderControl(relays){const statusById=new Map((State.status?.relays||[]).map(r=>[Number(r.id),r]));$('controlRelays').innerHTML=relays.map(item=>{const relay={...statusById.get(Number(item.id)),...item};const manual=relay.mode==='manual';return `<article class="control-card ${relay.state?'is-on':''}" data-relay="${relay.id}" data-collapsible data-collapse-key="control-relay-${relay.id}"><div class="control-title" data-collapse-header><div><h3>${escapeHtml(LABELS[relay.function]||relay.function||LABELS.none)}</h3></div><span class="mode-pill ${manual?'':'auto'}">${relay.state?'Encendida':'Apagada'} · ${manual?'Manual':'Automático'}</span></div><details class="connect-channel-settings"><summary>Configuración avanzada</summary><p class="field-help">Canal ${relay.id} · ${escapeHtml(relay.pin||'—')}</p><div class="control-fields"><label>Función<select data-field="function">${Object.entries(LABELS).map(([v,l])=>`<option value="${v}" ${v===relay.function?'selected':''}>${l}</option>`).join('')}</select></label><label>Modo<select data-field="mode"><option value="manual" ${manual?'selected':''}>Manual</option><option value="auto" ${!manual?'selected':''}>Automático</option></select></label></div></details><div class="control-actions">${manual?`<button class="relay-toggle ${relay.state?'on':''}" data-action="relay" data-state="${relay.state?'off':'on'}">${relay.state?'Apagar':'Encender'} · ${relay.state?'ON':'OFF'}</button>`:'<div class="auto-lock">◷ Control automático</div>'}<button class="secondary-button" data-action="save-function">Guardar función</button></div></article>`}).join('')}
  async function setRelay(id,state){return apiPost('/api/relay',{id,state})}
  async function saveRelayFunction(id,func,mode){return apiPost('/api/functions',{relay:id,function:func,mode})}
  async function refreshControl(){await loadStatus();await loadFunctions()}

  // Automatización
  async function loadDashboardConfig(){try{const data=await apiGet('/api/config');State.config=data;if(State.status)renderDashboardRelays(State.status.relays||[]);return data}catch{return null}}
  async function loadConfig(){try{const data=await apiGet('/api/config');State.config=data;if(State.status)renderDashboardRelays(State.status.relays||[]);const form=$('automationForm');form.elements.hora.value=data.lightStartHour;form.elements.min.value=data.lightStartMinute;form.elements.dur.value=data.lightDurationHours;form.elements.extendedTransition.checked=false;form.elements.tmin.value=data.tempMin;form.elements.tmax.value=data.tempMax;form.elements.ventMode.value=data.ventilationMode||'combined';form.elements.ventInterval.value=data.ventilationIntervalMinutes??10;form.elements.ventDuration.value=data.ventilationDurationMinutes??2;form.elements.ventEmergencyDuration.value=data.ventilationEmergencyDurationMinutes??3;const transition=$('lightTransitionStatus');if(data.lightTransitionActive){const action=data.lightTransitionMode==='hold_on'?'La luz permanecerá encendida':'La luz permanecerá apagada',until=data.lightTransitionUntil?new Date(Number(data.lightTransitionUntil)*1000).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'el próximo cambio';transition.textContent=`Transición activa: ${action} hasta ${until}.`}else transition.textContent='Sin transición pendiente.';return data}catch(error){showMessage('automationMessage',errorText(error),'error');throw error}}
  async function saveAutomationConfig(values){return apiPost('/api/config',values)}

  // Hardware
  async function loadHardware(){try{const[data,diagnostics]=await Promise.all([apiGet('/api/hardware'),apiGet('/api/diagnostics').catch(()=>null)]);State.hardware=data;State.diagnostics=diagnostics;renderHardware(data);renderDhtDiagnostics(diagnostics?.dht);return data}catch(error){showMessage('hardwareMessage',errorText(error),'error');throw error}}
  function renderHardware(data){const devices=[{key:'dht',name:data.dht?.type||'DHT21',pin:data.dht?.pin},{key:'relay1',name:'Relay 1',pin:data.relays?.find(r=>r.id===1)?.pin},{key:'relay2',name:'Relay 2',pin:data.relays?.find(r=>r.id===2)?.pin},{key:'relay3',name:'Relay 3',pin:data.relays?.find(r=>r.id===3)?.pin},{key:'relay4',name:'Relay 4',pin:data.relays?.find(r=>r.id===4)?.pin}];const pins=data.allowedDigitalPins||['D1','D2','D5','D6','D7'];$('hardwareFields').innerHTML=devices.map(d=>`<div class="hardware-item"><label><span>${d.name}</span><strong>${escapeHtml(d.pin||'—')}</strong></label><select name="${d.key}" aria-label="Pin de ${d.name}">${pins.map(pin=>`<option value="${pin}" ${pin===d.pin?'selected':''}>${pin}</option>`).join('')}</select></div>`).join('');updatePinOptions()}
  function updatePinOptions(){const selects=[...$('hardwareFields').querySelectorAll('select')];const used=new Set(selects.map(s=>s.value));selects.forEach(select=>[...select.options].forEach(option=>option.disabled=option.value!==select.value&&used.has(option.value)))}
  async function saveHardwareConfig(values){return apiPost('/api/hardware',values)}

  // Navegación y eventos UI
  document.addEventListener('click',event=>{const cancel=event.target.closest('button[value="cancel"]');if(!cancel)return;event.preventDefault();cancel.closest('dialog')?.close('cancel')},true)
  async function showView(view){if(!hardwareEnabled&&hardwareViews.includes(view))view="integrations";State.view=view;document.querySelectorAll('[data-view-panel]').forEach(n=>n.classList.toggle('active',n.dataset.viewPanel===view));document.querySelectorAll('[data-view]').forEach(n=>n.classList.toggle('active',n.dataset.view===(view==='lot'?'cultivation':view)));scrollTo({top:0,behavior:'smooth'});if(view==='dashboard'&&State.cultivoReady)await GrowToday.load();if(view==='cultivation'&&State.cultivoReady)await Cultivation.load().catch(error=>console.warn(error));if(view==='agenda'&&State.cultivoReady)await Agenda.load().catch(error=>console.warn(error));if(view==='operations'&&State.cultivoReady)await Operations.load().catch(error=>console.warn(error));if(view==='recipes'&&State.cultivoReady){await Products.load().catch(error=>console.warn(error));await Recipes.load().catch(error=>console.warn(error))}if(view==='assistant'&&State.cultivoReady)await GrowAssistant.refresh().catch(error=>console.warn(error));if(view==='team'&&State.cultivoReady)await Workspaces.load().catch(error=>console.warn(error));if(view==='control')await loadFunctions().catch(()=>{});if(view==='energy'){renderEnergyConfig();await renderEnergy().catch(()=>{})}if(view==='automation')await loadConfig().catch(()=>{});if(view==='hardware')await loadHardware().catch(()=>{})}
  async function refreshCentral(){if(!State.cultivoReady)return;await CultivoRepository.loadWorkspaces();Workspaces.renderSelector();await showView(State.view)}
  async function refreshFromButton(button){const label=button.textContent;button.disabled=true;button.textContent='↻';try{await refreshCentral()}catch(error){console.error('No se pudo actualizar Supabase:',error);$('cloudSyncStatus').textContent='Error de nube';$('cloudSyncStatus').className='cloud-sync error'}finally{button.disabled=false;button.textContent=label}}
  async function initNativeNavigation(){const nativeApp=globalThis.Capacitor?.Plugins?.App;if(!nativeApp)return;await nativeApp.addListener('backButton',()=>{const dialog=document.querySelector('dialog[open]');if(dialog){dialog.close('cancel');return}if(!$('authGate').hidden){nativeApp.exitApp();return}if(State.view!=='dashboard'){showView('dashboard');return}nativeApp.exitApp()})}
  document.addEventListener('click',event=>{const nav=event.target.closest('[data-view]');if(nav){$('mobileMoreMenu').hidden=true;$('mobileMoreButton').setAttribute('aria-expanded','false');showView(nav.dataset.view)}})
  $('mobileMoreButton').addEventListener('click',()=>{const menu=$('mobileMoreMenu'),open=menu.hidden;menu.hidden=!open;$('mobileMoreButton').setAttribute('aria-expanded',String(open))})
  $('closeMobileMore').addEventListener('click',()=>{$('mobileMoreMenu').hidden=true;$('mobileMoreButton').setAttribute('aria-expanded','false')})
  document.addEventListener('click',event=>{const tab=event.target.closest('[data-recipe-tab]');if(!tab)return;document.querySelectorAll('[data-recipe-tab]').forEach(node=>node.classList.toggle('active',node===tab));document.querySelectorAll('[data-recipe-panel]').forEach(node=>node.classList.toggle('active',node.dataset.recipePanel===tab.dataset.recipeTab));if(tab.dataset.recipeTab==='products')Products.load();else Recipes.load()})
  $('cloudRefresh').addEventListener('click',event=>refreshFromButton(event.currentTarget))
  $('mobileCloudRefresh').addEventListener('click',event=>refreshFromButton(event.currentTarget))
  $('themeToggle').addEventListener('click',toggleTheme)
  $('themeToggleMobile').addEventListener('click',toggleTheme)
  document.querySelectorAll('[data-environment-metric]').forEach(button=>button.addEventListener('click',()=>globalThis.EnvironmentHistory?.open(button.dataset.environmentMetric,State.status?.device||State.address,State.config)))
  addEventListener('grow-workspace-changed',()=>{if(State.cultivoReady){Cultivation.load().catch(()=>{});Agenda.load().catch(()=>{});Products.load().catch(()=>{});Recipes.load().catch(()=>{})}})
  addEventListener('grow-sync-status',event=>{const labels={syncing:'Sincronizando…',synced:'Nube sincronizada',cached:'Caché local',error:'Error de nube'};const node=$('cloudSyncStatus');node.textContent=labels[event.detail.state]||'Nube';node.className=`cloud-sync ${event.detail.state}`;$('mobileCloudStatus').textContent=node.textContent})
  $('controlRelays').addEventListener('click',async event=>{const button=event.target.closest('[data-action]');if(!button)return;const card=button.closest('[data-relay]');const id=card.dataset.relay;clearMessage('controlMessage');card.classList.add('is-busy');try{if(button.dataset.action==='relay'){await setRelay(id,button.dataset.state);showMessage('controlMessage',`Relay ${id} actualizado.`)}else{const func=card.querySelector('[data-field="function"]').value;const mode=card.querySelector('[data-field="mode"]').value;await saveRelayFunction(id,func,mode);showMessage('controlMessage',`Configuración del Relay ${id} guardada.`)}await refreshControl()}catch(error){showMessage('controlMessage',errorText(error),'error');await refreshControl().catch(()=>{})}finally{card.classList.remove('is-busy')}})
  $('automationForm').addEventListener('submit',event=>{event.preventDefault();clearMessage('automationMessage');const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));values.extendedTransition=form.elements.extendedTransition.checked?'1':'0';const h=Number(values.hora),m=Number(values.min),d=Number(values.dur),min=Number(values.tmin),max=Number(values.tmax),interval=Number(values.ventInterval),duration=Number(values.ventDuration),emergency=Number(values.ventEmergencyDuration);if(!Number.isInteger(h)||h<0||h>23)return showMessage('automationMessage','La hora debe estar entre 0 y 23.','error');if(!Number.isInteger(m)||m<0||m>59)return showMessage('automationMessage','Los minutos deben estar entre 0 y 59.','error');if(!Number.isInteger(d)||d<1||d>24)return showMessage('automationMessage','La duración debe estar entre 1 y 24 horas.','error');if(!Number.isFinite(min)||!Number.isFinite(max)||max<=min)return showMessage('automationMessage','La temperatura máxima debe ser mayor que la mínima.','error');if(!['interval','temperature','combined'].includes(values.ventMode))return showMessage('automationMessage','Seleccioná un modo de ventilación válido.','error');if(!Number.isInteger(interval)||interval<1||interval>1440)return showMessage('automationMessage','El intervalo debe estar entre 1 y 1440 minutos.','error');if(!Number.isInteger(duration)||duration<1||duration>60||duration>=interval)return showMessage('automationMessage','La duración debe ser menor que el intervalo y estar entre 1 y 60 minutos.','error');if(!Number.isInteger(emergency)||emergency<1||emergency>10)return showMessage('automationMessage','La emergencia debe durar entre 1 y 10 minutos.','error');busy(form.querySelector('[type="submit"]'),async()=>{try{const result=await saveAutomationConfig(values);await loadConfig();const transitionMessage=values.extendedTransition==='1'?(result.lightTransitionActive?'Horario guardado y transición extendida activa.':'Horario guardado. La transición no se activó: verificá que la luz esté en modo automático y que la hora esté sincronizada.'):'Automatización y ventilación guardadas en el Wemos.';showMessage('automationMessage',transitionMessage,result.lightTransitionActive||values.extendedTransition==='0'?'success':'error')}catch(error){showMessage('automationMessage',errorText(error),'error')}})})
  $('hardwareFields').addEventListener('change',updatePinOptions)
  $('hardwareForm').addEventListener('submit',event=>{event.preventDefault();clearMessage('hardwareMessage');const form=event.currentTarget;const values=Object.fromEntries(new FormData(form));if(new Set(Object.values(values)).size!==Object.values(values).length)return showMessage('hardwareMessage','Cada dispositivo debe usar un pin diferente.','error');busy(form.querySelector('[type="submit"]'),async()=>{try{const result=await saveHardwareConfig(values);await loadHardware();showMessage('hardwareMessage',result?.restartRequired===true?'La nueva asignación quedó guardada. Reiniciá el Wemos para aplicarla.':'Asignación de hardware guardada. Verificá si el Wemos requiere reinicio.','success')}catch(error){showMessage('hardwareMessage',errorText(error),'error')}})})
  $('connectionForm').addEventListener('submit',event=>{event.preventDefault();const form=event.currentTarget;const name=form.elements.deviceName.value.trim();const address=normalizeAddress(form.elements.deviceAddress.value);if(!name)return showMessage('connectionMessage','Ingresá un nombre para el dispositivo.','error');if(!address||/[\s/]/.test(address))return showMessage('connectionMessage','Ingresá una IP o hostname válido, sin rutas.','error');State.name=name;State.address=address;localStorage.setItem(CONFIG.nameKey,name);localStorage.setItem(CONFIG.addressKey,address);updateLocalIdentity();busy($('testConnection'),()=>loadStatus({notify:true}))})
  $('restoreConnection').addEventListener('click',()=>{$('deviceName').value=CONFIG.defaultName;$('deviceAddress').value=CONFIG.defaultAddress;showMessage('connectionMessage','Valores predeterminados restaurados en el formulario. Guardá para aplicarlos.','info')})
  document.addEventListener('click',event=>{if(event.target.closest('[data-restart-device]'))$('restartDeviceDialog').showModal()})
  $('closeRestartDevice').addEventListener('click',()=>$('restartDeviceDialog').close('cancel'))
  $('cancelRestartDevice').addEventListener('click',()=>$('restartDeviceDialog').close('cancel'))
  $('confirmRestartDevice').addEventListener('click',restartDevice)
  $('energyForm').addEventListener('submit',event=>{event.preventDefault();clearMessage('energyMessage');const form=event.currentTarget;const data=new FormData(form);const tariff=Number(data.get('tariff'));const devices=[1,2,3,4].map(relayId=>({relayId,name:String(data.get(`name${relayId}`)||'').trim(),watts:Number(data.get(`watts${relayId}`))}));if(!Number.isFinite(tariff)||tariff<0)return showMessage('energyMessage','El costo por kWh debe ser un número igual o mayor que cero.','error');if(devices.some(d=>!d.name))return showMessage('energyMessage','Todos los dispositivos necesitan un nombre.','error');if(devices.some(d=>!Number.isFinite(d.watts)||d.watts<0))return showMessage('energyMessage','Las potencias deben ser números iguales o mayores que cero.','error');Energy.saveEnergyConfig({tariff,devices});renderEnergyConfig();renderEnergy();showMessage('energyMessage','Configuración eléctrica guardada localmente.','success')})
  $('requestEnergyReset').addEventListener('click',()=>{$('resetConfirm').hidden=false})
  $('cancelEnergyReset').addEventListener('click',()=>{$('resetConfirm').hidden=true})
  $('confirmEnergyReset').addEventListener('click',async()=>{const button=$('confirmEnergyReset');await busy(button,async()=>{try{await Energy.clearHistory();if(State.status)await Energy.trackStatus(State.status.relays);await renderEnergy();$('resetConfirm').hidden=true;showMessage('energyMessage','Histórico de consumo eliminado. La configuración se conservó.','success')}catch(error){showMessage('energyMessage',errorText(error),'error')}})})
  document.addEventListener('visibilitychange',()=>{if(document.hidden){State.suspended=true;if(State.energyReady)Energy.markOffline()}else{State.suspended=false;loadStatus();refreshCentral().catch(error=>console.warn('No se pudo refrescar la nube al reanudar:',error))}})
  function updateLocalIdentity(){$('brandName').textContent=State.name;$('mobileBrandName').textContent=State.name;$('deviceName').value=State.name;$('deviceAddress').value=State.address}
  async function getAssistantDeviceContext(){if(!hardwareEnabled)return{enabled:false};try{const config=await apiGet('/api/config');State.config=config;return{connected:true,device:State.name,address:State.address,temperature:State.status?.temperature??null,humidity:State.status?.humidity??null,sensor:State.status?.dht||null,config,relays:(State.status?.relays||[]).map(({id,function:relayFunction,mode,state})=>({id,function:relayFunction,mode,state}))}}catch{return{connected:false,device:State.name,address:State.address,lastKnownConfig:State.config,sensor:State.status?.dht||null}}}
  globalThis.GrowNavigation=Object.freeze({showView});
  globalThis.GrowDevice=Object.freeze({getAssistantContext:getAssistantDeviceContext,isEnabled:()=>hardwareEnabled});

  async function startCentralDomain(user){if(centralUserId===user.id)return;centralUserId=user.id;try{await CultivoRepository.init();await Workspaces.init();State.cultivoReady=true;const presenceClient=globalThis.Capacitor?.isNativePlatform?.()?'android':'web';await CultivoRepository.touchPresence(presenceClient);clearInterval(presenceTimer);presenceTimer=setInterval(()=>{if(!document.hidden)CultivoRepository.touchPresence(presenceClient)},60000);try{const invitationResult=await CultivoRepository.acceptPendingInvitations(user.email);if(invitationResult.accepted){await Workspaces.load();$('cloudSyncStatus').title=`Se aceptaron ${invitationResult.accepted} invitación(es) y se abrió el cultivo compartido.`}}catch(invitationError){console.warn('La invitación automática no bloqueó la carga de proyectos:',invitationError)}await GrowToday.load();await CultivoMigration.prompt(user);$('cloudSyncStatus').textContent='Nube sincronizada';$('cloudSyncStatus').className='cloud-sync synced';await OnboardingTour.maybeStart()}catch(error){console.error('No se pudo iniciar el dominio centralizado:',error);$('cloudSyncStatus').textContent='Error de proyectos';$('cloudSyncStatus').title=error.message;$('cloudSyncStatus').className='cloud-sync error';const teamMessage=$('teamMessage');if(teamMessage){teamMessage.textContent=`No se pudieron cargar tus proyectos: ${error.message}`;teamMessage.className='message show error'}}}
  async function boot(){initConnect();applyTheme(localStorage.getItem(CONFIG.themeKey)||'light');updateLocalIdentity();renderDashboardRelays([]);renderOfflineTime();renderEnergyConfig();GrowDaily.init();GrowToday.init();Cultivation.init();Agenda.init();Operations.init();Products.init();Recipes.init();NutritionCalendar.init();GrowAssistant.init();VoiceAssistant.init();CultivoMigration.init();OnboardingTour.init();await initNativeNavigation();try{await CultivoDB.init()}catch(error){console.warn('No se pudo inicializar flora-cultivo-db:',error)}try{await Energy.initEnergyDB();State.energyReady=true}catch(error){showMessage('energyMessage','No se pudo abrir el histórico local. El control del Wemos seguirá funcionando.','error')}await GrowAuth.init(startCentralDomain);if(hardwareEnabled){await Promise.all([loadStatus(),loadDashboardConfig()]);setInterval(loadStatus,CONFIG.pollMs);setInterval(renderOfflineTime,1000);setInterval(()=>{if(State.energyReady)renderEnergy().catch(()=>{})},30000)}}
  boot();
})();
