(()=>{'use strict';
const $=id=>document.getElementById(id);
const steps=[
  {view:'dashboard',selector:'[data-view-panel="dashboard"] .page-heading',icon:'⌂',title:'Hoy',description:'Tu panorama diario: atención, próximos trabajos, tandas y actividad reciente. El ambiente y los detalles del dispositivo siguen disponibles.'},
  {view:'cultivation',selector:'[data-view-panel="cultivation"] .page-heading',icon:'✦',title:'Cultivos, espacios y lotes',description:'Un proyecto puede contener varios cultivos simultáneos. Dentro de cada uno organizás espacios —como Vegetativo o Floración— y lotes independientes —madres, esquejes o tandas SOG— con fechas, etapas y cantidades propias.'},
  {view:'cultivation',selector:'[data-view-panel="cultivation"] .hub-switch',icon:'↔',title:'El universo Cultivo',description:'Desde este selector alternás entre Cultivos y lotes y Recetas e insumos. Los lotes son la unidad que después vincula eventos, registros de bitácora y planificación nutricional.'},
  {view:'recipes',selector:'[data-view-panel="recipes"] .page-heading',icon:'◇',title:'Recetas e insumos',description:'Armá fórmulas reutilizables para riego, nutrición o aplicaciones foliares. Cada receta puede reunir productos, dosis por litro y una etapa de uso; los insumos conservan la información de cada producto.'},
  {view:'recipes',selector:'[data-view-panel="recipes"] .module-tabs',icon:'≋',title:'Biblioteca organizada',description:'Usá Recetas para consultar y editar fórmulas, e Insumos para administrar los productos disponibles. Luego podés relacionar una receta con una actividad real de la bitácora.'},
  {view:'agenda',face:'events',selector:'[data-view-panel="agenda"] .agenda-face-switch',icon:'▣',title:'El universo Agenda',description:'Agenda reúne tres miradas conectadas: Calendario para planificar, Nutrición para seguir el programa del lote y Bitácora para registrar lo que realmente ocurrió.'},
  {view:'agenda',face:'events',selector:'[data-view-panel="agenda"] .agenda-toolbar',icon:'⌗',title:'Filtros y responsabilidades',description:'Cambiá de mes y filtrá por cultivo o lote, por eventos asignados a vos y por activos o archivados. Cada evento puede tener responsables, participantes, prioridad, recurrencia y estado.'},
  {view:'agenda',face:'events',selector:'[data-view-panel="agenda"] .agenda-calendar-panel',icon:'□',title:'Calendario y línea de cultivo',description:'Acá conviven las tareas con las líneas temporales de cada lote y sus fases reales. Así podés leer en una misma fecha qué cultivo está activo, en qué etapa se encuentra y qué trabajo corresponde.'},
  {view:'agenda',face:'nutrition',selector:'[data-view-panel="agenda"] .agenda-face-switch',icon:'◫',title:'Calendario nutricional',description:'Compara semana y etapa esperadas con la etapa real confirmada. Permite asociar una tabla diferente a cada lote, revisar pH y EC objetivo y detectar si el cultivo está alineado, adelantado o atrasado.'},
  {view:'operations',selector:'[data-view-panel="operations"] .page-heading',icon:'☷',title:'Bitácora: lo que realmente pasó',description:'Registrá riegos, fertilizaciones, aplicaciones foliares, podas, trasplantes, esquejes, controles de plagas, observaciones, incidentes, cortes de luz y cambios del sistema. Podés asociar cada registro al cultivo o lote correcto.'},
  {view:'operations',selector:'[data-view-panel="operations"] .journal-toolbar',icon:'⌕',title:'Trazabilidad consultable',description:'Filtrá por tipo, lote y período o buscá por texto. Esta historia permite reconstruir el ciclo, comparar la planificación con la ejecución y analizar al final qué funcionó y qué conviene mejorar.'},
  {view:'assistant',selector:'[data-view-panel="assistant"] .assistant-panel',icon:'✦',title:'Asistente IA',description:'Consultá el proyecto o describí en lenguaje natural lo que hiciste. La IA prepara eventos y registros vinculados; vos revisás la propuesta antes de que se guarde.'},
  {view:'control',selector:'[data-view-panel="control"] .control-shortcuts',icon:'◉',title:'Control y hardware',description:'Operá el Wemos y accedé a automatización, ventilación, sensores, energía, conexión y diagnósticos. El control físico está separado de la planificación del cultivo.'},
  {view:'team',selector:'[data-view-panel="team"] .page-heading',icon:'◎',title:'Proyectos y miembros',description:'Cambiá de proyecto, invitá personas y administrá sus permisos. Cada miembro ve solamente los proyectos a los que fue incorporado; el proyecto de muestra permanece aislado.'}
];
let index=0,ready=false;
function showView(view){document.querySelector(`[data-view="${view}"]`)?.click()}
function clearHighlight(){document.querySelectorAll('.tour-highlight').forEach(node=>node.classList.remove('tour-highlight'))}
function render(){const step=steps[index];showView(step.view);if(step.face)document.querySelector(`[data-agenda-face="${step.face}"]`)?.click();clearHighlight();requestAnimationFrame(()=>{const target=document.querySelector(step.selector);target?.classList.add('tour-highlight');target?.scrollIntoView({block:'center',behavior:'smooth'})});$('tourIcon').textContent=step.icon;$('tourTitle').textContent=step.title;$('tourDescription').textContent=step.description;$('tourEyebrow').textContent=`RECORRIDO · ${index+1} DE ${steps.length}`;$('tourPrevious').disabled=index===0;$('tourNext').textContent=index===steps.length-1?'Finalizar':'Siguiente';$('tourProgress').innerHTML=steps.map((_,i)=>`<i class="${i<=index?'active':''}"></i>`).join('')}
async function finish(){clearHighlight();$('appTourDialog').close();await CultivoRepository.completeOnboarding().catch(console.warn);showView('dashboard')}
function start(){index=0;$('projectHubDialog')?.close();if(!$('appTourDialog').open)$('appTourDialog').show();render()}
async function maybeStart(){try{const state=await CultivoRepository.getOnboardingState();if(state.completed)return;const dialog=$('welcomeWizardDialog');if(!dialog.open)dialog.showModal()}catch(error){console.warn('No se pudo iniciar el onboarding:',error)}}
function init(){if(ready)return;ready=true;$('welcomeWizardForm').addEventListener('change',event=>{if(event.target.name==='mode')$('welcomeProjectName').hidden=event.target.value==='demo'});$('welcomeWizardForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,data=Object.fromEntries(new FormData(form)),button=event.submitter,status=$('welcomeWizardMessage');button.disabled=true;status.className='message show info';status.textContent='Preparando tu experiencia…';try{if(data.mode==='demo'){const demo=CultivoRepository.getWorkspaces().find(item=>item.isDemo);if(demo)await CultivoRepository.setCurrentWorkspace(demo.id)}else await CultivoRepository.createOnboardingWorkspace(data.name.trim(),data.mode);await Workspaces.load();$('welcomeWizardDialog').close();start()}catch(error){status.className='message show error';status.textContent=error.message}finally{button.disabled=false}});$('welcomeSkipTour').addEventListener('click',async()=>{await CultivoRepository.completeOnboarding();$('welcomeWizardDialog').close()});$('tourPrevious').addEventListener('click',()=>{if(index>0){index--;render()}});$('tourNext').addEventListener('click',()=>{if(index===steps.length-1)finish();else{index++;render()}});$('tourExit').addEventListener('click',finish);$('startTourButton').addEventListener('click',start)}
globalThis.OnboardingTour=Object.freeze({init,maybeStart,start});
})();
